/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./*.html"],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#d4e8cc",
        "surface-dim": "#d8dbd4",
        "surface-variant": "#e0e4dc",
        "on-secondary-container": "#202e1c",
        "on-secondary-fixed": "#0f1f0e",
        "secondary-container": "#d1e6c9",
        "on-tertiary-container": "#faf8f3",
        "inverse-primary": "#afd191",
        "tertiary-container": "#72726e",
        "primary": "#45622e",
        "on-primary-container": "#edffd9",
        "error-container": "#ffdad6",
        "inverse-surface": "#2d312c",
        "tertiary-fixed": "#e4e2dd",
        "primary-fixed-dim": "#afd191",
        "surface-tint": "#4a6632",
        "on-tertiary-fixed-variant": "#2c2c29",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#0c2000",
        "outline": "#4b5043",
        "surface": "#ffffff",
        "primary-fixed": "#cbedab",
        "on-background": "#191d18",
        "background": "#ffffff",
        "on-primary-fixed-variant": "#334e1c",
        "surface-container-highest": "#e0e4dc",
        "surface-container": "#ecefe7",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#c8c6c2",
        "on-primary": "#ffffff",
        "outline-variant": "#c4c8ba",
        "surface-container-high": "#e6e9e2",
        "on-secondary-fixed-variant": "#3a4b36",
        "primary-container": "#5d7b44",
        "surface-container-low": "#f2f5ed",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#1b1c19",
        "error": "#ba1a1a",
        "tertiary": "#31312d",
        "on-surface": "#191d18",
        "inverse-on-surface": "#eff2ea",
        "secondary-fixed-dim": "#b8ccb1",
        "on-error": "#ffffff",
        "secondary": "#2f3e2a",
        "on-surface-variant": "#2a2f26",
        "surface-bright": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "lg": "48px",
        "sm": "12px",
        "margin-desktop": "64px",
        "base": "8px",
        "xl": "80px",
        "margin-mobile": "20px",
        "gutter": "24px",
        "xs": "4px",
        "md": "24px"
      },
      fontFamily: {
        "body-md": ["Be Vietnam Pro"],
        "headline-lg": ["Be Vietnam Pro"],
        "headline-xl": ["Be Vietnam Pro"],
        "headline-lg-mobile": ["Be Vietnam Pro"],
        "headline-md": ["Be Vietnam Pro"],
        "body-lg": ["Be Vietnam Pro"],
        "label-md": ["Be Vietnam Pro"],
        "headline-xl-mobile": ["Be Vietnam Pro"]
      },
      fontSize: {
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "headline-xl-mobile": ["36px", {"lineHeight": "44px", "fontWeight": "700"}]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
